import {
  GET_INDEX_ARTICLES,
  GET_ARTICLE,
  GET_ARTICLE_LIST,
  GET_ARTICLE_ISLIKE,
  GET_ARTICLE_LIKE_COUNT,
  GET_RECOMMEND_ARTICLE,
  DO_LIKE_ARTICLE,
  DO_DISLIKE_ARTICLE,
  DO_COMMIT_ARTICLE,
  DO_TEMP_ARTICLE,
  DO_ADD_ARTCILE_READ,
  DO_DELETE_ARTICLE,
} from '@/store/article-actions';
import {
  GET_USER_INFO,
  GET_USER_FANS,
  GET_USER_SUBSCRIBERS,
  GET_USER_LATEST_ARTICLES,
  GET_USER_ARTICLES,
  GET_USER_RECORD,
  DO_USER_LOGIN,
  DO_USER_REGISTER,
  DO_USER_UPDATE,
  DO_USER_PASSWORD_UPDATE,
  DO_USER_PASSWORD_VALIDATE,
} from '@/store/user-actions.js';
import {
  DO_ARTICLE_COMMENT,
  DO_ARTICLE_COMMENT_REPLY,
  GET_ARTICLE_COMMENTS,
} from '@/store/comment-actions';
import {
  DO_SUBSCRIBE_USER,
  DO_REMOVE_SUBSCRIBE,
  GET_IS_SUBSCRIBE,
} from '@/store/subscribe-actions';

import { GET_NOTICE_LIST } from '@/store/message-actions.js';
import { DO_ACCESS_ADD } from '@/store/access-actions.js';
import {
  DO_ADD_FAVORITE,
  DO_DELETE_FAVORITE,
  DO_ADD_FAVORITE_GROUP,
  DO_DELETE_FAVORITE_GROUP,
  GET_FAVORITE_GROUP_LIST,
  GET_FAVORITE_LIST,
  GET_FAVORITE_INFO
} from '@/store/favorite-actions.js';
// store actions
export default {
  //article-actions
  GET_INDEX_ARTICLES,
  GET_ARTICLE,
  GET_ARTICLE_LIST,
  GET_ARTICLE_ISLIKE,
  GET_ARTICLE_LIKE_COUNT,
  GET_RECOMMEND_ARTICLE,
  DO_LIKE_ARTICLE,
  DO_DISLIKE_ARTICLE,
  DO_COMMIT_ARTICLE,
  DO_TEMP_ARTICLE,
  DO_ADD_ARTCILE_READ,
  DO_DELETE_ARTICLE,
  // user-actions
  GET_USER_INFO,
  GET_USER_SUBSCRIBERS,
  GET_USER_FANS,
  GET_USER_LATEST_ARTICLES,
  GET_USER_ARTICLES,
  GET_USER_RECORD,
  DO_USER_LOGIN,
  DO_USER_REGISTER,
  DO_USER_UPDATE,
  DO_USER_PASSWORD_UPDATE,
  DO_USER_PASSWORD_VALIDATE,
  // comment-actions
  DO_ARTICLE_COMMENT,
  DO_ARTICLE_COMMENT_REPLY,
  GET_ARTICLE_COMMENTS,
  // subscribe-actions
  DO_SUBSCRIBE_USER,
  DO_REMOVE_SUBSCRIBE,
  GET_IS_SUBSCRIBE,
  //message-actions
  GET_NOTICE_LIST,
  // access-actions
  DO_ACCESS_ADD,
  // favorite-actions
  DO_ADD_FAVORITE,
  DO_DELETE_FAVORITE,
  DO_ADD_FAVORITE_GROUP,
  DO_DELETE_FAVORITE_GROUP,
  GET_FAVORITE_GROUP_LIST,
  GET_FAVORITE_LIST,
  GET_FAVORITE_INFO
};
