import {
  GET_ALL_ARTICLES,
  GET_ARTICLE,
  GET_ARTICLE_ISLIKE,
  GET_ARTICLE_LIKE_COUNT,
  DO_LIKE_ARTICLE,
  DO_DISLIKE_ARTICLE,
  DO_PUBLISH_ARTICLE,
} from '@/store/article-actions';
import {
  GET_USER_INFO,
  GET_USER_SUBSCRIBERS,
  GET_USER_ARTICLES,
  DO_USER_LOGIN,
  DO_USER_REGISTER,
  DO_USER_UPDATE,
  DO_USER_PASSWORD_UPDATE,
  DO_USER_PASSWORD_VALIDATE,
} from '@/store/user-actions.js';
import {
  DO_ARTICLE_COMMENT,
  DO_ARTICLE_COMMENT_REPLY,
  GET_ARTICLE_COMMENTS,
} from '@/store/comment-actions';
import {
  DO_SUBSCRIBE_USER,
  DO_REMOVE_SUBSCRIBE,
  GET_IS_SUBSCRIBE,
} from '@/store/subscribe-actions';
// store actions
export default {
  //article-actions
  GET_ALL_ARTICLES,
  GET_ARTICLE,
  GET_ARTICLE_ISLIKE,
  GET_ARTICLE_LIKE_COUNT,
  DO_LIKE_ARTICLE,
  DO_DISLIKE_ARTICLE,
  DO_PUBLISH_ARTICLE,
  // user-actions
  GET_USER_INFO,
  GET_USER_SUBSCRIBERS,
  GET_USER_ARTICLES,
  DO_USER_LOGIN,
  DO_USER_REGISTER,
  DO_USER_UPDATE,
  DO_USER_PASSWORD_UPDATE,
  DO_USER_PASSWORD_VALIDATE,
  // comment-actions
  DO_ARTICLE_COMMENT,
  DO_ARTICLE_COMMENT_REPLY,
  GET_ARTICLE_COMMENTS,
  // subscribe-actions
  DO_SUBSCRIBE_USER,
  DO_REMOVE_SUBSCRIBE,
  GET_IS_SUBSCRIBE,
};
